Added JSON schema
ietf-wg-httpapi/rfc7807bis pull request #18
Opened 2021-04-23 14:11 UTC by sdatspun2

2021-04-23 14:15 UTC, sdatspun2 commented
This PR is for Issue #8

2021-04-26 02:42 UTC, mnot requested changes
See inline.

2021-04-26 02:42 UTC, mnot commented on schema/json/problem.json
> +      "description": "The HTTP status code (RFC7231, Section 6) generated by the origin server for this occurrence of the problem."
Might be worth adding a `minimum` of `100` and a `maximum` of `599`.

2021-04-26 02:42 UTC, mnot commented on schema/json/problem.json
> +      "format": "uri",
```suggestion
      "format": "uri-reference",
```

2021-04-26 02:42 UTC, mnot commented on schema/json/problem.json
> +      "format": "uri",
```suggestion
      "format": "uri-reference",
```

2021-04-26 02:42 UTC, mnot commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Is this the right URI? I'm not up to speed on the latest in schema-land...

2021-04-26 02:42 UTC, mnot commented on schema/json/problem_details.json
> +  "x-examples": {
Shouldn't this be `examples` and an array, as per http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.9.5 ?

2021-04-26 02:42 UTC, mnot commented on schema/json/problem_details.json
> +    }
We should remove this until the spec text is in place -- it's not clear we're going to go this way.

2021-04-26 02:42 UTC, mnot commented on schema/json/problem_details.json
> +      ]
Same as above, should be removed until the issue is settled.

2021-04-26 13:52 UTC, sdatspun2 commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-5

I kept it slightly old to increase adoption. Latest is 2020-12. Other option could be 2019-09. if not draft7, we could use 2019-09. Lmk.

https://json-schema.org/specification-links.html

2021-04-26 14:02 UTC, sdatspun2 commented on schema/json/problem_details.json
> +  "x-examples": {
Hmm...relied on a tool. Fixing in next commit.

2021-04-26 14:03 UTC, sdatspun2 commented on schema/json/problem_details.json
> +    }
Ohk...

2021-04-26 14:03 UTC, sdatspun2 commented on schema/json/problem.json
> +      "description": "The HTTP status code (RFC7231, Section 6) generated by the origin server for this occurrence of the problem."
Next commit.

2021-04-26 14:03 UTC, sdatspun2 commented on schema/json/problem.json
> +      "format": "uri",
Yes. Relative should be supported. Next commit.

2021-04-26 14:04 UTC, sdatspun2 commented on schema/json/problem.json
> +      "format": "uri",
+1

2021-04-29 09:56 UTC, dret commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
not sure about the "best" version/URI to choose, as they're still in eternal draft mode.

2021-04-29 09:57 UTC, dret commented on schema/json/problem_details.json
> +    }
"going to go this way" meaning adding a JSON schema, @mnot?

2021-04-30 00:10 UTC, mnot commented on schema/json/problem_details.json
> +    }
No, I mean we haven't resolved how multiple problems should be handled.

2021-05-01 00:59 UTC, sdatspun2 commented on schema/json/problem_details.json
> +    }
The schema proposal is an attempt to resolve it :)

2021-05-01 01:01 UTC, sdatspun2 commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
I am thinking of removing it. Some linters do not recognize $schema, esp. those that follow pre OpenAPI 3.1 spec.

2021-05-01 01:15 UTC, darrelmiller commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
We use the following 
```
 "$schema": "https://json-schema.org/draft/2020-12/schema",
```
in the [OpenAPI 3.1 metaschema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.json) and it has been reviewed by the JSON Schema editors.

2021-06-17 03:59 UTC, mnot commented on schema/json/problem_details.json
> +    }
Right, but this is a proposal to resolve the issue about having a JSON Schema, not that. Addressing two issues together conflates them, and we haven't yet come to consensus on the latter. 

In this situation, the usual process is to address the more straightforward thing first -- in this case, adding a JSON Schema -- and then adding to it when we resolve the other issue. So I'd suggest removing `properties` for now (although we might add it back later).

2021-06-17 03:59 UTC, mnot commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Sounds good to me - let's change to that value.

2021-06-18 05:24 UTC, sdatspun2 commented on schema/json/problem_details.json
> +    }
Removed

2021-06-18 05:24 UTC, sdatspun2 commented on schema/json/problem_details.json
> +      ]
Removed

2021-06-18 05:25 UTC, sdatspun2 commented on schema/json/problem_details.json
> +  "x-examples": {
not relevant. removed.

2021-06-18 05:25 UTC, sdatspun2 commented on schema/json/problem.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Changed

2021-06-18 07:24 UTC, mnot approved these changes
LGTM

2021-07-05 16:45 UTC, merged